from .calc_editor_common import (
    CalcCondition,
    CalcEditorField,
    CalcEditorFieldType,
    CalcFieldSource,
    CalcFieldSourceKind,
    CalcRevealBy,
    CalcSubmit,
)
from .choice_card import ChoiceCardProps, ChoiceCardSubmit, ChoiceOption
from .constructions_editor import (
    CherdachnyeSubtype,
    ConstructionEntry,
    ConstructionLayer,
    ConstructionLayerKind,
    ConstructionType,
    ConstructionTypeConfig,
    ConstructionsCity,
    ConstructionsEditorProps,
    ConstructionsFieldSource,
    ConstructionsFieldSourceKind,
    ConstructionsGeneral,
    ConstructionsGeneralSources,
)
from .flex_table import FlexTableCell, FlexTableProps, FlexTableRow
from .form_card import (
    FormCardProps,
    FormCardSubmit,
    FormField,
    FormFieldLookupValue,
    FormFieldType,
    LookupSuggestMode,
)
from .insolation_editor import (
    InsolationBuilding,
    InsolationEditorProps,
    InsolationNotice,
    InsolationPoint,
    InsolationPointTemplate,
)
from .insolation_report import (
    InsolationReportAction,
    InsolationReportCheck,
    InsolationReportInputChip,
    InsolationReportInputGroup,
    InsolationReportInputs,
    InsolationReportProps,
    InsolationReportProtocol,
    InsolationReportVerdict,
    InsolationTimeline,
    InsolationTimelineSegment,
    InsolationTimelineTick,
)
from .keo_editor import (
    KeoComputedNoteEntry,
    KeoComputedNotes,
    KeoEditorProps,
    KeoEditorRoom,
    KeoEditorRoomTemplate,
    KeoEditorSection,
    KeoValidationRule,
    KeoValidationRuleKind,
)
from .keo_report import (
    KeoReportAction,
    KeoReportInputChip,
    KeoReportInputGroup,
    KeoReportInputs,
    KeoReportProps,
    KeoReportProtocol,
    KeoReportRecommendation,
    KeoReportRoom,
    KeoReportVerdict,
)
from .latex_formula import LatexFormulaProps
from .lift_editor import (
    LiftEditorDependentRule,
    LiftEditorDependentRuleRow,
    LiftEditorDependentRuleSource,
    LiftEditorField,
    LiftEditorFieldOptionsBy,
    LiftEditorFieldScope,
    LiftEditorFieldSource,
    LiftEditorFieldSourceKind,
    LiftEditorFieldType,
    LiftEditorMethodConfig,
    LiftEditorProps,
    LiftEditorRecommend,
    LiftEditorRecommendParam,
    LiftsMode,
)
from .shared import CellPrimitive, StrictModel, TextAlign
from .simple_table import SimpleTableColumn, SimpleTableProps, SimpleTableRow

COMPONENT_MODELS = {
    "SimpleTable": SimpleTableProps,
    "FlexTable": FlexTableProps,
    "LatexFormula": LatexFormulaProps,
    "ChoiceCard": ChoiceCardProps,
    "FormCard": FormCardProps,
    "ConstructionsEditor": ConstructionsEditorProps,
    # Новый рендерер того же экрана на новых примитивах: схема props общая со
    # старым, поэтому и модель одна (change constructions-editor-next).
    "ConstructionsEditorNext": ConstructionsEditorProps,
    "LiftEditor": LiftEditorProps,
    # То же и у лифтов: имя новое, схема props общая со старым рендерером
    # (change lift-editor-next).
    "LiftEditorNext": LiftEditorProps,
    "KeoEditor": KeoEditorProps,
    # То же и у КЕО: имя новое, схема props общая со старым рендерером
    # (change keo-editor-next).
    "KeoEditorNext": KeoEditorProps,
    "KeoReport": KeoReportProps,
    # Новый рендерер того же отчёта на примитивах каталога: схема props общая
    # со старым, поэтому и модель одна (change keo-report-next).
    "KeoReportNext": KeoReportProps,
    "InsolationEditor": InsolationEditorProps,
    "InsolationReport": InsolationReportProps,
}

__all__ = [
    "COMPONENT_MODELS",
    "CalcCondition",
    "CalcEditorField",
    "CalcEditorFieldType",
    "CalcFieldSource",
    "CalcFieldSourceKind",
    "CalcRevealBy",
    "CalcSubmit",
    "CellPrimitive",
    "CherdachnyeSubtype",
    "ChoiceCardProps",
    "ChoiceCardSubmit",
    "ChoiceOption",
    "ConstructionEntry",
    "ConstructionLayer",
    "ConstructionLayerKind",
    "ConstructionType",
    "ConstructionTypeConfig",
    "ConstructionsCity",
    "ConstructionsEditorProps",
    "ConstructionsFieldSource",
    "ConstructionsFieldSourceKind",
    "ConstructionsGeneral",
    "ConstructionsGeneralSources",
    "FlexTableCell",
    "FlexTableProps",
    "FlexTableRow",
    "FormCardProps",
    "FormCardSubmit",
    "FormField",
    "FormFieldLookupValue",
    "FormFieldType",
    "InsolationBuilding",
    "InsolationEditorProps",
    "InsolationNotice",
    "InsolationPoint",
    "InsolationPointTemplate",
    "InsolationReportAction",
    "InsolationReportCheck",
    "InsolationReportInputChip",
    "InsolationReportInputGroup",
    "InsolationReportInputs",
    "InsolationReportProps",
    "InsolationReportProtocol",
    "InsolationReportVerdict",
    "InsolationTimeline",
    "InsolationTimelineSegment",
    "InsolationTimelineTick",
    "KeoComputedNoteEntry",
    "KeoComputedNotes",
    "KeoEditorProps",
    "KeoEditorRoom",
    "KeoEditorRoomTemplate",
    "KeoEditorSection",
    "KeoReportAction",
    "KeoReportInputChip",
    "KeoReportInputGroup",
    "KeoReportInputs",
    "KeoReportProps",
    "KeoReportProtocol",
    "KeoReportRecommendation",
    "KeoReportRoom",
    "KeoReportVerdict",
    "KeoValidationRule",
    "KeoValidationRuleKind",
    "LatexFormulaProps",
    "LiftEditorDependentRule",
    "LiftEditorDependentRuleRow",
    "LiftEditorDependentRuleSource",
    "LiftEditorField",
    "LiftEditorFieldOptionsBy",
    "LiftEditorFieldScope",
    "LiftEditorFieldSource",
    "LiftEditorFieldSourceKind",
    "LiftEditorFieldType",
    "LiftEditorMethodConfig",
    "LiftEditorProps",
    "LiftEditorRecommend",
    "LiftEditorRecommendParam",
    "LiftsMode",
    "LookupSuggestMode",
    "SimpleTableColumn",
    "SimpleTableProps",
    "SimpleTableRow",
    "StrictModel",
    "TextAlign",
]
